name: Pylint

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    build:
        name: Formatter
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10"]

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install autoflake black isort pylint

            - name: autoflake
              run: autoflake -r $(git ls-files '*.py')

            - name: black
              run: black $(git ls-files '*.py')

            - name: isort
              run: isort $(git ls-files '*.py')

            - name: Analysing the code with pylint
              run: |
                  pylint $(git ls-files '*.py')

            - name: Auto Commit
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Apply Code Formatter
